### ISSUE TITLE
Design of the test plan

### ISSUE THREAD

**Issue by joseabernal** [maxbernal/SeededImageSegmentationProject#20]
We need to design a test plan for the application. We should decide which elements are we going to consider for testing.
- A template for the test plan should be created.

**Comment by glemaitre** [comment]
Congrats guys,

https://github.com/google/googletest
Can be helpful.

You can check this link to know how to set it up within cmake
https://github.com/glemaitre/traffic-sign-detection

**Comment by joseabernal** [comment]
I found this template for the test plan. I think we can use it. [se-test-doc-template.pdf](https://github.com/maxbernal/SeededImageSegmentationProject/files/38163/se-test-doc-template.pdf)

**Comment by joseabernal** [comment]
Covered by unit tests implemented in Issue #44 .
