### ISSUE TITLE
Create a parameters file

### ISSUE THREAD

**Issue by glemaitre** [maxbernal/SeededImageSegmentationProject#29]
Hey guys,

I am doing a round of the different project of SE. I see that I have nothing to teach to you guys ;)
Only small thing that I did not see (does not mean that you did not do it, I went pretty fast through) is regarding the parameters.

Do you think that it could be a nice feature to manage them inside an external file and load it at execution time. It could allow to not have to recompile in case that you want to change one of them.

but anyway more than enough for a basic project.

**Comment by joseabernal** [comment]
Very good suggestion. Thanks

**Comment by rcdaudt** [comment]
Jose is the boss, I still have a lot to learn :)

Thanks for the suggestion! We'll look into that

**Comment by glemaitre** [comment]
Watching the code, sure he would kick my butt ;)
I have to go back in my dusty C++ books ;)

**Comment by joseabernal** [comment]
This task will be moved to closed since, so far, we don't have lot of parameters to consider. It is a good approach for Internationalization, but it is out of the current scope of the project.
